#!/usr/bin/env bash
#
# Interactive setup for nomad-token-menubar. Walks you through the token-fetch
# method, tests it, and writes ~/.nomad-token-menubar/config.sh for you.
# Safe to re-run to reconfigure.

set -uo pipefail

DATA_DIR="${NOMAD_MENUBAR_DIR:-$HOME/.nomad-token-menubar}"
CONFIG="$DATA_DIR/config.sh"
REFRESH="$DATA_DIR/lib/refresh.sh"

bold() { printf '\033[1m%s\033[0m\n' "$*"; }
ok()   { printf '\033[32m%s\033[0m\n' "$*"; }
err()  { printf '\033[31m%s\033[0m\n' "$*"; }

ask() { # ask <prompt> [default] -> prints answer
  local p="$1" d="${2:-}" a
  if [[ -n "$d" ]]; then read -r -p "$p [$d]: " a; printf '%s' "${a:-$d}"
  else read -r -p "$p: " a; printf '%s' "$a"; fi
}
sq() { # single-quote-escape a string for safe writing into a sourced file
  printf "'%s'" "$(printf '%s' "$1" | sed "s/'/'\\\\''/g")"
}

[[ -t 0 ]] || { err "setup.sh needs an interactive terminal."; exit 1; }
mkdir -p "$DATA_DIR"

bold "nomad-token-menubar — setup"
echo "This writes $CONFIG"
echo

if [[ -f "$CONFIG" ]] && grep -Eq "^[[:space:]]*REFRESH_CMD=[\"']?[^\"'[:space:]]" "$CONFIG"; then
  a="$(ask "A config already exists — overwrite it? (y/N)" "N")"
  [[ "$a" == [yY] ]] || { echo "Keeping existing config. Nothing changed."; exit 0; }
  echo
fi

echo "How do you fetch a Nomad token?"
echo "  1) Vault Nomad secrets engine   (vault read <mount>/creds/<role>)"
echo "  2) Nomad ACL auth method / OIDC (nomad login -method=<method>)"
echo "  3) A custom command or script that prints a token"
choice="$(ask "Choose 1/2/3" "1")"
echo

REFRESH_CMD=""; EXPIRY=""; NOMAD_ADDR=""

case "$choice" in
  1)
    mount="$(ask "Vault mount path" "nomad")"
    role="$(ask "Nomad creds role" "nomad-admin")"
    REFRESH_CMD="r=\$(vault read -format=json ${mount}/creds/${role}); echo \"\$r\" | jq -r .data.secret_id; echo \"\$r\" | jq -r .lease_duration"
    EXPIRY="self"  # unused (TTL comes from the lease on line 2), harmless default
    ;;
  2)
    method="$(ask "Nomad ACL auth method name" "")"
    NOMAD_ADDR="$(ask "NOMAD_ADDR" "${NOMAD_ADDR:-}")"
    REFRESH_CMD="nomad login -method=${method} -json | jq -r .SecretID"
    EXPIRY="self"
    ;;
  3)
    echo "Enter the command that prints a fresh token on stdout (line 1)."
    REFRESH_CMD="$(ask "REFRESH_CMD" "")"
    has_ttl="$(ask "Does it also print the TTL in seconds on line 2? (y/N)" "N")"
    if [[ "$has_ttl" == [yY] ]]; then
      EXPIRY="self"
    else
      exp="$(ask "Token lifetime — seconds (e.g. 3600), or 'self' to ask Nomad" "3600")"
      EXPIRY="$exp"
      [[ "$exp" == "self" ]] && NOMAD_ADDR="$(ask "NOMAD_ADDR" "")"
    fi
    ;;
  *) err "Invalid choice."; exit 1 ;;
esac

[[ -n "$REFRESH_CMD" ]] || { err "No REFRESH_CMD given."; exit 1; }

# --- test it ------------------------------------------------------------------
# Capture stdout (the token) and stderr (diagnostics) separately, exactly as
# refresh.sh will: the token must appear on stdout, not be an error message.
echo
bold "Testing your command…"
errf="$(mktemp)"
out="$(eval "$REFRESH_CMD" 2>"$errf")" || true
tok="$(printf '%s\n' "$out" | sed -n '1p')"
ttl="$(printf '%s\n' "$out" | sed -n '2p' | tr -d '[:space:]')"
if [[ -n "$tok" ]]; then
  ok "✓ got a token (${#tok} chars)$([[ "$ttl" =~ ^[0-9]+$ ]] && echo ", TTL ${ttl}s")"
else
  err "✗ no token produced."
  [[ -s "$errf" ]] && { echo "  stderr:"; sed 's/^/    /' "$errf"; }
  a="$(ask "Save this config anyway? (y/N)" "N")"
  [[ "$a" == [yY] ]] || { rm -f "$errf"; echo "Aborted; nothing written."; exit 1; }
fi
rm -f "$errf"

# --- write config -------------------------------------------------------------
{
  echo "# nomad-token-menubar configuration (generated by setup.sh $(date +%F))"
  echo "REFRESH_CMD=$(sq "$REFRESH_CMD")"
  [[ -n "$EXPIRY"     ]] && echo "EXPIRY=$(sq "$EXPIRY")"
  [[ -n "$NOMAD_ADDR" ]] && echo "NOMAD_ADDR=$(sq "$NOMAD_ADDR")"
} > "$CONFIG"
chmod 600 "$CONFIG"
echo
ok "Wrote $CONFIG"

# --- first fetch --------------------------------------------------------------
if [[ -x "$REFRESH" ]]; then
  a="$(ask "Fetch a token now and light up the menu bar? (Y/n)" "Y")"
  if [[ "$a" != [nN] ]]; then
    if "$REFRESH"; then ok "✓ Done — check your menu bar."; else err "Fetch failed; try the Refresh button later."; fi
  fi
fi
echo "You can re-run this anytime: $DATA_DIR/setup.sh"
